### ISSUE TITLE
Block Time History endpoint

### ISSUE THREAD

**Issue by sirkitree** [sirkitree/cosmos-middleware-neos#12]
PolyLogiX is working on something to display a line chart dynamically in Neos. We'll need data for this. 

The line graph data that populates this component on https://cosmos.bigdipper.live/ is what we're after here.
![The Big Dipper _ Cosmos Explorer by Forbole - Google Chrome 2019-05-14 10 06 30](https://user-images.githubusercontent.com/28543/57717367-f5bf3480-762f-11e9-903e-b2a10949c4e1.png)

## Tasks
- [ ]  figure out where we can get this data
- [ ] create a new endpoint for getting the data for the block time history
- [ ] talk with PolyLogiX to determine what format the Neos component will need the data in

## Questions
**must have answers before work begins**
1. Will the chart in it's current state be compatible with a JSON formatted response?
    1. Yes, this will accept JSON and the output should be formatted as such.
1. What format would be best for the JSON response?

**Comment by sirkitree** [comment]
@satanasov here is another one I can pay you for your time on in NCR if you're up for it.
